#!/bin/bash

#SBATCH --partition gpu
#SBATCH --gres gpu:1
#SBATCH --time 0-02:00
#SBATCH --mem=64GB

# Print some information about the job
echo "Running on host $(hostname)"
echo "Time is $(date)"
echo "Directory is $(pwd)"
echo "Slurm job ID is $SLURM_JOB_ID"
echo "Number of visible devices = $CUDA_VISIBLE_DEVICES"
echo
echo "This job runs on the following machines:"
echo "$SLURM_JOB_NODELIST" | uniq
echo

# Run the Python script
srun cd great-ape-behaviour-detector
srun python main.py
